### ISSUE TITLE
Добавить класс для планшетных устройств 

### ISSUE THREAD

**Issue by MSupreme1990** [studio107/flexy#12]
Добавить класс который делит блоки на две колонки для планшетных устройств.

Пример костыля:

```scss
&_ipad {
    @include flexy-device(ipad-1-2-portrait) {
      .b-block-grid__item {
        flex-basis: 50%;
      }
    }
  }
```
